<a href="https://colab.research.google.com/github/Satyake/TF-ZTM/blob/main/ZTM_NLP_TFDan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:




















































#ZTM NLP
!wget https://github.com/mrdbourke/tensorflow-deep-learning/blob/main/extras/helper_functions.py

--2023-09-21 02:10:37--  https://github.com/mrdbourke/tensorflow-deep-learning/blob/main/extras/helper_functions.py
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 54004 (53K) [text/plain]
Saving to: ‘helper_functions.py’

helper_functions.py 100%[===================>]  52.74K  --.-KB/s    in 0.03s   

2023-09-21 02:10:37 (1.97 MB/s) - ‘helper_functions.py’ saved [54004/54004]



In [ ]:
#NLP Dataset  Disaster/Not Disaster

In [ ]:
!wget https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip

--2023-09-21 02:10:38--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 108.177.12.207, 172.217.193.207, 172.217.204.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|108.177.12.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: ‘nlp_getting_started.zip’

nlp_getting_started 100%[===================>] 593.11K  --.-KB/s    in 0.005s  

2023-09-21 02:10:38 (116 MB/s) - ‘nlp_getting_started.zip’ saved [607343/607343]



In [ ]:
import zipfile
f=zipfile.ZipFile('/content/nlp_getting_started.zip')
f.extractall()
f.close()

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
train_df=pd.read_csv('/content/train.csv')
test_df=pd.read_csv('/content/test.csv')

In [ ]:
train_df['text'][1]

'Forest fire near La Ronge Sask. Canada'

In [ ]:
#shuffle dataframe
train_df_shuffled=train_df.sample(frac=1, random_state=42)

In [ ]:
train_df_shuffled.head()

id      keyword               location  \
2644  3796  destruction                    NaN   
2227  3185       deluge                    NaN   
5448  7769       police                     UK   
132    191   aftershock                    NaN   
6845  9810       trauma  Montgomery County, MD   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0

In [ ]:
test_df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [ ]:
train_df['target'].value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
train_sentences,val_sentences, train_labels,val_labels=train_test_split(train_df_shuffled['text'],train_df_shuffled['target'],test_size=0.1, random_state=42)

In [ ]:
len(train_sentences), len(val_sentences),len(train_labels),len(val_labels)

(6851, 762, 6851, 762)

In [ ]:
train_sentences=train_sentences.to_numpy()
val_sentences=val_sentences.to_numpy()
train_labels=train_labels.to_numpy()
val_labels=val_labels.to_numpy()

In [ ]:
import tensorflow as tf


In [ ]:
text_vectorizer=tf.keras.layers.experimental.preprocessing.TextVectorization(max_tokens=None, #automatically add tokens with <OOV>  #word that does not fit will get OOV
                                                                             standardize="lower_and_strip_punctuation",
                                                                             split='whitespace',
                                                                             ngrams=None,      #group of N words
                                                                             output_mode="int", #map tokens to numbers
                                                                             output_sequence_length=None, #How long are the sequences

                                                                             )


In [ ]:
len(train_sentences[0].split())

7

In [ ]:
#find avg no of tokens (words) in training tweets
round(sum([len(i.split()) for i in train_sentences]))/len(train_sentences)


14.901036345059115

In [ ]:
#setup text vectorizer variables
max_vocab_length=10000 #max no of words to have in our vocabulary
max_length=15 #max len of the sequences

text_vectorizer=tf.keras.layers.experimental.preprocessing.TextVectorization(max_tokens=max_vocab_length,
                                                                             output_mode='int',
                                                                             output_sequence_length=max_length)
#map the text vectorizer to the training data
text_vectorizer.adapt(train_sentences)

In [ ]:
sample_sentence="There is a flood on the street"
text_vectorizer(sample_sentence)

<tf.Tensor: shape=(15,), dtype=int64, numpy=
array([ 74,   9,   3, 232,  11,   2, 698,   0,   0,   0,   0,   0,   0,
         0,   0])>

In [ ]:
words_in_vocab=text_vectorizer.get_vocabulary()
top_5_words=words_in_vocab[:5]
bottom_5_words=words_in_vocab[:-5]

In [ ]:
bottom_5_words

['',
 '[UNK]',
 'the',
 'a',
 'in',
 'to',
 'of',
 'and',
 'i',
 'is',
 'for',
 'on',
 'you',
 'my',
 'with',
 'it',
 'that',
 'at',
 'by',
 'this',
 'from',
 'be',
 'are',
 'was',
 'have',
 'like',
 'as',
 'up',
 'so',
 'just',
 'but',
 'me',
 'im',
 'your',
 'not',
 'amp',
 'out',
 'its',
 'will',
 'an',
 'no',
 'has',
 'fire',
 'after',
 'all',
 'when',
 'we',
 'if',
 'now',
 'via',
 'new',
 'more',
 'get',
 'or',
 'about',
 'what',
 'he',
 'people',
 'news',
 'been',
 'over',
 'one',
 'how',
 'dont',
 'they',
 'who',
 'into',
 'were',
 'do',
 'us',
 '2',
 'can',
 'video',
 'emergency',
 'there',
 'disaster',
 'than',
 'police',
 'would',
 'his',
 'still',
 'her',
 'some',
 'body',
 'storm',
 'crash',
 'burning',
 'suicide',
 'back',
 'man',
 'california',
 'why',
 'time',
 'them',
 'had',
 'buildings',
 'rt',
 'first',
 'cant',
 'see',
 'got',
 'day',
 'off',
 'our',
 'going',
 'nuclear',
 'know',
 'world',
 'bomb',
 'fires',
 'love',
 'killed',
 'go',
 'attack',
 'youtube',
 'dead

In [ ]:
from tensorflow.keras import layers
embedding=layers.Embedding(input_dim=max_vocab_length,
                           output_dim=128,
                           input_length=max_length)

In [ ]:
#get random sentence from train and generate embedding from the embedding layer
import random

random_sentence=random.choice(train_sentences)
print(f'random_sentence: {random_sentence}')
print(f'embedded_sentence: {embedding(text_vectorizer(random_sentence))}')

random_sentence: Silence. #Palermo #Shipwreck #Children #Deaths http://t.co/Tm9ZBHJcyf
embedded_sentence: [[ 0.00457364 -0.00940273  0.02889464 ...  0.03085785 -0.04234315
  -0.00717884]
 [-0.02974978  0.00807125  0.04021383 ...  0.01114502 -0.04552934
   0.03865707]
 [ 0.01588737  0.00674098 -0.00567865 ... -0.02475892 -0.0085871
  -0.03724914]
 ...
 [ 0.04571204 -0.03577994  0.00838894 ... -0.04620463  0.02680886
  -0.04649322]
 [ 0.04571204 -0.03577994  0.00838894 ... -0.04620463  0.02680886
  -0.04649322]
 [ 0.04571204 -0.03577994  0.00838894 ... -0.04620463  0.02680886
  -0.04649322]]


In [ ]:
sample_embed=embedding(text_vectorizer(random_sentence))

In [ ]:
sample_embed.shape, sample_embed[0]

(TensorShape([15, 128]),
 <tf.Tensor: shape=(128,), dtype=float32, numpy=
 array([ 0.00457364, -0.00940273,  0.02889464,  0.04719443, -0.03896569,
        -0.02875977,  0.01856693,  0.0201615 ,  0.02793792, -0.041038  ,
        -0.03918718,  0.04908688,  0.02188106,  0.02180493, -0.01114808,
        -0.00662172,  0.0041746 , -0.04288185,  0.01353706, -0.03882179,
        -0.02261244, -0.02824333,  0.00464145,  0.03524517,  0.00058072,
         0.01141491, -0.03413232, -0.00835771, -0.03440117,  0.00221284,
        -0.01977577,  0.01663369,  0.02175288, -0.00874569,  0.0244917 ,
         0.00429084,  0.04563105,  0.01808119, -0.00583119, -0.04700998,
         0.01600948,  0.01456466,  0.01192849, -0.00712197,  0.01248949,
        -0.04272156, -0.00470244,  0.00612756, -0.0142521 , -0.0016176 ,
        -0.02173158, -0.04904035, -0.01235685, -0.04856066,  0.03073487,
        -0.0431654 , -0.02249696, -0.02081621,  0.01262248,  0.04241763,
         0.04430449,  0.04455082, -0.01034319,  0.

In [ ]:
#baseline model
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

#create tokenization and pipeline
model_0=Pipeline([
      ('tfidf',TfidfVectorizer()),
      ('clf',MultinomialNB())])
#fit the pipeline with the training_data

model_0.fit(train_sentences,train_labels)


Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [ ]:
#evaluate the baseline
baseline_score=model_0.score(val_sentences, val_labels )
print(f"Baseline Model Acc {baseline_score}")

Baseline Model Acc 0.7926509186351706


In [ ]:
train_df.target.value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [ ]:
predictions=model_0.predict(val_sentences)
predictions[:10]

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def calculate_results(y_true,y_pred):
  model_accuracy=accuracy_score(y_true,y_pred)
  #calculate prec and rec and f1 score
  model_precision, model_recall, model_f1,_=precision_recall_fscore_support(y_true,y_pred,average='weighted')
  model_results={ "accuracy": model_accuracy,
                 "precision": model_precision,
                  "recall":model_recall,
                  "f1": model_f1}
  return model_results



In [ ]:
calculate_results(val_labels, predictions)

{'accuracy': 0.7926509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1': 0.7862189758049549}

In [ ]:
#Model1: Dense Model FNN
from tensorflow.keras import layers
inputs=layers.Input(shape=(1,), dtype=tf.string) #inputs are 1-dimensional string
x=text_vectorizer(inputs)#turn text to numbers
x=embedding(x) #create embedding of numbers
#x=layers.GlobalAveragePooling1D()(x) #condense the feature vector for each token to one vector
x=layers.GlobalMaxPool1D()(x)
outputs=layers.Dense(1, activation='sigmoid')(x)

model1=tf.keras.Model(inputs=inputs, outputs=outputs)

ValueError: ignored

In [ ]:
model1.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (Text  (None, 15)                0         
 Vectorization)                                                  
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 global_max_pooling1d (Glob  (None, 128)               0         
 alMaxPooling1D)                                                 
                                                                 
 dense (Dense)               (None, 1)                 129       
                                                                 
Total params: 1280129 (4.88 MB)
Trainable params: 1280129 (4.

In [ ]:
#compile the model
model1.compile(loss="binary_crossentropy",optimizer=tf.keras.optimizers.Adam(),metrics=['accuracy'])

In [ ]:
#train_labels=train_labels.reshape(-1,1)
#val_labels=val_labels.reshape(-1,1)

In [ ]:

h_mode1=model1.fit(train_sentences, train_labels,epochs=5, validation_data=(val_sentences,val_labels))

Epoch 1/5
215/215 [==============================] - 11s 42ms/step - loss: 0.6408 - accuracy: 0.6535 - val_loss: 0.5787 - val_accuracy: 0.7507
Epoch 2/5
215/215 [==============================] - 8s 35ms/step - loss: 0.4697 - accuracy: 0.8256 - val_loss: 0.4743 - val_accuracy: 0.7900
Epoch 3/5
215/215 [==============================] - 9s 40ms/step - loss: 0.3415 - accuracy: 0.8740 - val_loss: 0.4467 - val_accuracy: 0.7953
Epoch 4/5
215/215 [==============================] - 8s 35ms/step - loss: 0.2593 - accuracy: 0.9072 - val_loss: 0.4498 - val_accuracy: 0.7913
Epoch 5/5
215/215 [==============================] - 6s 26ms/step - loss: 0.1989 - accuracy: 0.9333 - val_loss: 0.4683 - val_accuracy: 0.7940


In [ ]:
train_labels.shape, val_labels.shape

((6851,), (762,))

In [ ]:
val_labels

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,

In [ ]:
model1.evaluate(val_sentences, val_labels)

24/24 [==============================] - 0s 2ms/step - loss: 0.4683 - accuracy: 0.7940


[0.4682807922363281, 0.7939632534980774]

In [ ]:
predictions=model1.predict(val_sentences)

24/24 [==============================] - 0s 2ms/step


In [ ]:
predictions.shape


(762, 1)

In [ ]:
predictions=tf.squeeze(predictions)
predictions=tf.round(predictions)
predictions[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0.], dtype=float32)>

In [ ]:
calculate_results(predictions,val_labels)

{'accuracy': 0.7939632545931758,
 'precision': 0.8116936173208233,
 'recall': 0.7939632545931758,
 'f1': 0.7970767520494241}

In [ ]:
words_in_vocab=text_vectorizer.get_vocabulary()
len(words_in_vocab),words_in_vocab[:10]

(10000, ['', '[UNK]', 'the', 'a', 'in', 'to', 'of', 'and', 'i', 'is'])

In [ ]:
#get the weight matrix of the embedding layer
#embed_weights=model1.get_layer('embedding').get_weights()[0]

In [ ]:
#embed_weights.shape#same size as vocab length

In [ ]:
#import io
#out_v = io.open('vectors.tsv', 'w', encoding='utf-8')
#out_m = io.open('metadata.tsv', 'w', encoding='utf-8')

#for index, word in enumerate(words_in_vocab):
#  if index == 0:
#    continue  # skip 0, it's padding.
#  vec = embed_weights[index]
#  out_v.write('\t'.join([str(x) for x in vec]) + "\n")
#  out_m.write(word + "\n")
#out_v.close()
#out_m.close()

In [ ]:
#RNNs
from tensorflow.keras import layers

inputs=layers.Input(shape=(1,),dtype=tf.string)
x=text_vectorizer(inputs)
x=embedding(x)
print(x.shape)
x=layers.LSTM(64,return_sequences=True,activation='tanh')(x) #when stacking RNN cells, need to return sequences=True
print(x.shape)
x=layers.LSTM(8)(x)
print(x.shape)
outputs=layers.Dense(1, activation='sigmoid')(x)
model=tf.keras.Model(inputs=inputs, outputs=outputs,name='LSTM-RNN')

(None, 15, 128)
(None, 15, 64)
(None, 8)


In [ ]:
model.summary()

Model: "LSTM-RNN"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (TextV  (None, 15)               0         
 ectorization)                                                   
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 lstm (LSTM)                 (None, 15, 64)            49408     
                                                                 
 lstm_1 (LSTM)               (None, 8)                 2336      
                                                                 
 dense_1 (Dense)             (None, 1)                 9         
                                                          

In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(),metrics=['accuracy'],loss='binary_crossentropy')

In [ ]:
model_2_history=model.fit(train_sentences,train_labels,validation_data=(val_sentences,val_labels),epochs=5)

Epoch 1/5
215/215 [==============================] - 15s 50ms/step - loss: 0.3839 - accuracy: 0.8364 - val_loss: 0.4924 - val_accuracy: 0.7743
Epoch 2/5
215/215 [==============================] - 9s 43ms/step - loss: 0.2495 - accuracy: 0.9041 - val_loss: 0.5226 - val_accuracy: 0.7769
Epoch 3/5
215/215 [==============================] - 9s 42ms/step - loss: 0.1750 - accuracy: 0.9383 - val_loss: 0.6340 - val_accuracy: 0.7795
Epoch 4/5
215/215 [==============================] - 9s 40ms/step - loss: 0.1323 - accuracy: 0.9550 - val_loss: 0.7741 - val_accuracy: 0.7467
Epoch 5/5
215/215 [==============================] - 9s 44ms/step - loss: 0.1018 - accuracy: 0.9634 - val_loss: 0.7924 - val_accuracy: 0.7625


In [ ]:
model_2_pred_probs=model.predict(val_sentences)

24/24 [==============================] - 1s 6ms/step


In [ ]:
model_2_preds=tf.squeeze(tf.round(model_2_pred_probs))
model_2_preds

<tf.Tensor: shape=(762,), dtype=float32, numpy=
array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1.,
       1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0.,
       0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0.,
       1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0

In [ ]:
model_2_results=calculate_results(y_pred=model_2_preds,y_true=val_labels)
model_2_results

{'accuracy': 0.7624671916010499,
 'precision': 0.7661237980682454,
 'recall': 0.7624671916010499,
 'f1': 0.7592074612720654}

In [ ]:
#GRU

In [ ]:
from tensorflow.keras import layers
input=layers.Input(shape=(1,),dtype=tf.string)
x=text_vectorizer(input)
x=embedding(x)
x=tf.keras.layers.GRU(64, return_sequences=True)(x)
x=tf.keras.layers.LSTM(64,return_sequences=True)(x)
x=tf.keras.layers.GRU(64)(x)
x=tf.keras.layers.Dense(64, activation='relu')(x)
output=tf.keras.layers.Dense(1,activation='sigmoid')(x)
model3=tf.keras.Model(inputs=input,outputs=output)
model3.summary()


Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (TextV  (None, 15)               0         
 ectorization)                                                   
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 gru (GRU)                   (None, 15, 64)            37248     
                                                                 
 lstm_2 (LSTM)               (None, 15, 64)            33024     
                                                                 
 gru_1 (GRU)                 (None, 64)                24960     
                                                           

In [ ]:
model3.compile(loss='binary_crossentropy',
               optimizer='adam',
               metrics=['accuracy'])

In [ ]:
model3_history=model3.fit(train_sentences,train_labels, epochs=5, validation_data=(val_sentences,val_labels))

Epoch 1/5
215/215 [==============================] - 22s 65ms/step - loss: 0.1817 - accuracy: 0.9399 - val_loss: 0.7499 - val_accuracy: 0.7612
Epoch 2/5
215/215 [==============================] - 13s 61ms/step - loss: 0.0954 - accuracy: 0.9658 - val_loss: 0.8648 - val_accuracy: 0.7520
Epoch 3/5
215/215 [==============================] - 13s 62ms/step - loss: 0.0840 - accuracy: 0.9669 - val_loss: 1.0488 - val_accuracy: 0.7533
Epoch 4/5
215/215 [==============================] - 12s 57ms/step - loss: 0.0686 - accuracy: 0.9733 - val_loss: 0.9795 - val_accuracy: 0.7454
Epoch 5/5
215/215 [==============================] - 13s 61ms/step - loss: 0.0678 - accuracy: 0.9723 - val_loss: 0.9764 - val_accuracy: 0.7677


In [ ]:
model3_pred_probs=model3.predict(val_sentences)
model_3_preds=tf.squeeze(tf.round(model3_pred_probs))
model_3_preds[:10]
model_3_results=calculate_results(y_true=model_3_preds,y_pred=val_labels)
model_3_results

24/24 [==============================] - 1s 10ms/step


{'accuracy': 0.7677165354330708,
 'precision': 0.7750701420943072,
 'recall': 0.7677165354330708,
 'f1': 0.7693864249335994}

In [ ]:
inputs=layers.Input(shape=(1,),dtype=tf.string)
x=text_vectorizer(inputs)
x=embedding(x)
x=layers.Bidirectional(layers.LSTM(64,return_sequences=True))(x)
x=layers.Bidirectional(layers.GRU(6))(x)
outputs=layers.Dense(1,activation='sigmoid')(x)
model4=tf.keras.Model(inputs=inputs,outputs=outputs)
model4.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (TextV  (None, 15)               0         
 ectorization)                                                   
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 bidirectional (Bidirectiona  (None, 15, 128)          98816     
 l)                                                              
                                                                 
 bidirectional_1 (Bidirectio  (None, 12)               4896      
 nal)                                                            
                                                           

In [ ]:
model4.compile(optimizer='rmsprop',metrics=['accuracy'],loss='binary_crossentropy')

In [ ]:
history_model_4=model4.fit(train_sentences,train_labels,validation_data=(val_sentences,val_labels),epochs=5)

Epoch 1/5
215/215 [==============================] - 22s 61ms/step - loss: 0.1366 - accuracy: 0.9581 - val_loss: 0.7571 - val_accuracy: 0.7572
Epoch 2/5
215/215 [==============================] - 11s 53ms/step - loss: 0.0727 - accuracy: 0.9750 - val_loss: 0.9107 - val_accuracy: 0.7703
Epoch 3/5
215/215 [==============================] - 11s 52ms/step - loss: 0.0611 - accuracy: 0.9766 - val_loss: 1.0659 - val_accuracy: 0.7021
Epoch 4/5
215/215 [==============================] - 11s 50ms/step - loss: 0.0584 - accuracy: 0.9765 - val_loss: 0.9944 - val_accuracy: 0.7730
Epoch 5/5
215/215 [==============================] - 10s 47ms/step - loss: 0.0558 - accuracy: 0.9785 - val_loss: 1.0485 - val_accuracy: 0.7677


In [ ]:
model_4_probs=model4.predict(val_sentences)
model_4_preds=tf.squeeze(tf.round(model_4_probs))
model_4_preds.shape
model_4_results=calculate_results(model_4_preds,val_labels)
model_4_results

24/24 [==============================] - 2s 10ms/step


{'accuracy': 0.7677165354330708,
 'precision': 0.7811410349068685,
 'recall': 0.7677165354330708,
 'f1': 0.770447698442265}

In [ ]:
embedding_test=embedding(text_vectorizer(["this is a test sentence"]))
conv1d=layers.Conv1D(filters=32,kernel_size=5,activation='relu',padding='same')(embedding_test)
maxpool=layers.GlobalAveragePooling1D()(conv1d)

In [ ]:
conv1d.shape,maxpool.shape

(TensorShape([1, 15, 32]), TensorShape([1, 32]))

In [ ]:
maxpool

<tf.Tensor: shape=(1, 32), dtype=float32, numpy=
array([[0.        , 0.01423608, 0.01112109, 0.07238651, 0.02626864,
        0.00592963, 0.05710757, 0.00082992, 0.00507808, 0.0318867 ,
        0.01012723, 0.00348156, 0.05517615, 0.00076933, 0.00291509,
        0.00633459, 0.01074907, 0.0182513 , 0.08675881, 0.05487722,
        0.00990941, 0.00637404, 0.04767623, 0.00437496, 0.03062723,
        0.00390982, 0.00217744, 0.03329603, 0.        , 0.0180801 ,
        0.11077278, 0.02542171]], dtype=float32)>

In [ ]:
inputs=layers.Input(shape=(1,),dtype=tf.string)
x=text_vectorizer(inputs)
x=embedding(x)
x=layers.Conv1D(64, 5,activation='relu',padding="valid")(x)
x=layers.GlobalAveragePooling1D()(x)
outputs=layers.Dense(1,activation='sigmoid')(x)
model_5=tf.keras.Model(inputs=inputs,outputs=outputs)
model_5.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (TextV  (None, 15)               0         
 ectorization)                                                   
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 conv1d_1 (Conv1D)           (None, 11, 64)            41024     
                                                                 
 global_average_pooling1d_1   (None, 64)               0         
 (GlobalAveragePooling1D)                                        
                                                                 
 dense_5 (Dense)             (None, 1)                 65  

In [ ]:
model_5.compile(optimizer='adam',metrics=['accuracy'],loss='binary_crossentropy')
model5_history=model_5.fit(train_sentences,train_labels,validation_data=(val_sentences,val_labels),epochs=5)

Epoch 1/5
215/215 [==============================] - 7s 26ms/step - loss: 0.2131 - accuracy: 0.9296 - val_loss: 0.7248 - val_accuracy: 0.7520
Epoch 2/5
215/215 [==============================] - 6s 29ms/step - loss: 0.1181 - accuracy: 0.9590 - val_loss: 0.8499 - val_accuracy: 0.7428
Epoch 3/5
215/215 [==============================] - 5s 24ms/step - loss: 0.0910 - accuracy: 0.9658 - val_loss: 0.9423 - val_accuracy: 0.7598
Epoch 4/5
215/215 [==============================] - 6s 28ms/step - loss: 0.0773 - accuracy: 0.9710 - val_loss: 1.1069 - val_accuracy: 0.7690
Epoch 5/5
215/215 [==============================] - 5s 24ms/step - loss: 0.0663 - accuracy: 0.9740 - val_loss: 1.1108 - val_accuracy: 0.7467


In [ ]:
model5_pred_probs=model_5.predict(val_sentences)
model_5_preds=tf.squeeze(tf.round(model5_pred_probs))
model_5_results=calculate_results(model_5_preds,val_labels)
model_5_results

24/24 [==============================] - 0s 3ms/step


{'accuracy': 0.7467191601049868,
 'precision': 0.7490742817567593,
 'recall': 0.7467191601049868,
 'f1': 0.7474325103016676}

In [ ]:
#TL in NLP from tensorflowHub

In [ ]:
import tensorflow_hub as hub
embed=hub.load('https://tfhub.dev/google/universal-sentence-encoder/4')
embed_samples=embed([sample_sentence,
                     "when you call the universal sentence encoder it turns them into numbers"])


In [ ]:
embed_samples.shape

TensorShape([2, 512])

In [ ]:
sentence_encoder_layer=hub.KerasLayer('https://tfhub.dev/google/universal-sentence-encoder/4',trainable=False,name='USE-sentence-encoder',input_shape=[],dtype=tf.string)


In [ ]:
model_6=tf.keras.Sequential([
    sentence_encoder_layer,
    tf.keras.layers.Dense(64,activation='relu'),
    tf.keras.layers.Dense(1,activation='sigmoid')
])

In [ ]:
model_6.compile(loss='binary_crossentropy',metrics=['accuracy'],optimizer='adam')

In [ ]:
model_6.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 USE-sentence-encoder (Keras  (None, 512)              256797824 
 Layer)                                                          
                                                                 
 dense_6 (Dense)             (None, 64)                32832     
                                                                 
 dense_7 (Dense)             (None, 1)                 65        
                                                                 
Total params: 256,830,721
Trainable params: 32,897
Non-trainable params: 256,797,824
_________________________________________________________________


In [ ]:
history_model_6_TL=model_6.fit(train_sentences,train_labels,validation_data=(val_sentences,val_labels),epochs=5)

Epoch 1/5
215/215 [==============================] - 7s 15ms/step - loss: 0.5021 - accuracy: 0.7910 - val_loss: 0.4513 - val_accuracy: 0.8018
Epoch 2/5
215/215 [==============================] - 3s 12ms/step - loss: 0.4149 - accuracy: 0.8159 - val_loss: 0.4417 - val_accuracy: 0.8071
Epoch 3/5
215/215 [==============================] - 3s 13ms/step - loss: 0.4025 - accuracy: 0.8187 - val_loss: 0.4373 - val_accuracy: 0.8110
Epoch 4/5
215/215 [==============================] - 4s 17ms/step - loss: 0.3933 - accuracy: 0.8256 - val_loss: 0.4290 - val_accuracy: 0.8150
Epoch 5/5
215/215 [==============================] - 3s 13ms/step - loss: 0.3870 - accuracy: 0.8281 - val_loss: 0.4283 - val_accuracy: 0.8123


In [ ]:
model_6_probs=model_6.predict(val_sentences)
model_6_preds=tf.squeeze(tf.round(model_6_probs))
results=calculate_results(val_labels,model_6_preds)
results

24/24 [==============================] - 1s 9ms/step


{'accuracy': 0.8123359580052494,
 'precision': 0.8152105639975652,
 'recall': 0.8123359580052494,
 'f1': 0.8105808468856647}

In [ ]:
import pandas as pd

In [ ]:
#train_10_percent=train_df_shuffled[['text','target']].sample(frac=0.1)
#train_10_percent.head(), len(train_10_percent)
#train_sentences_10_percent=train_10_percent['text'].to_list()
#train_labels_10_percent=train_10_percent['target'].to_list()
train_10_percent_split=int(0.1*len(train_sentences))
train_10_percent=train_sentences[:685]
train_labels_10_percent=train_labels[:train_10_percent_split]
pd.Series(train_labels_10_percent).value_counts()

0    406
1    279
dtype: int64

In [ ]:
#train_10_percent['target'].value_counts()

In [ ]:
model_7=tf.keras.models.clone_model(model_6)

In [ ]:
model_7.compile(optimizer='adam',metrics=['accuracy'],loss='binary_crossentropy')


In [ ]:
history_model_7_TL_10_percent=model_7.fit(train_10_percent,train_labels_10_percent,validation_data=(val_sentences,val_labels),epochs=5)

Epoch 1/5
22/22 [==============================] - 8s 106ms/step - loss: 0.6661 - accuracy: 0.7314 - val_loss: 0.6434 - val_accuracy: 0.7546
Epoch 2/5
22/22 [==============================] - 1s 55ms/step - loss: 0.5938 - accuracy: 0.8102 - val_loss: 0.5858 - val_accuracy: 0.7612
Epoch 3/5
22/22 [==============================] - 1s 66ms/step - loss: 0.5187 - accuracy: 0.8219 - val_loss: 0.5341 - val_accuracy: 0.7743
Epoch 4/5
22/22 [==============================] - 2s 70ms/step - loss: 0.4606 - accuracy: 0.8175 - val_loss: 0.5017 - val_accuracy: 0.7848
Epoch 5/5
22/22 [==============================] - 1s 62ms/step - loss: 0.4189 - accuracy: 0.8277 - val_loss: 0.4892 - val_accuracy: 0.7822


In [ ]:
model_7_pred_probs=model_7.predict(val_sentences)
model_7_preds=tf.squeeze(tf.round(model_7_pred_probs))
model_7_results=calculate_results(model_7_preds,val_labels)
model_7_results

24/24 [==============================] - 1s 18ms/step


{'accuracy': 0.7821522309711286,
 'precision': 0.786270250701421,
 'recall': 0.7821522309711286,
 'f1': 0.7831549719752489}

In [ ]:
#saving and loading a trained model


In [ ]:
model_7.save('NLP_TL_model.h5')

In [ ]:
loaded_model=tf.keras.models.load_model('NLP_TL_model.h5',
                                        custom_objects={"KerasLayer":hub.KerasLayer})

In [ ]:
!wget https://storage.googleapis.com/ztm_tf_course/08_model_6_USE_feature_extractor.zip

--2023-08-20 13:33:56--  https://storage.googleapis.com/ztm_tf_course/08_model_6_USE_feature_extractor.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.101.128, 142.250.141.128, 142.251.2.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.101.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 960779165 (916M) [application/zip]
Saving to: ‘08_model_6_USE_feature_extractor.zip’

08_model_6_USE_feat 100%[===================>] 916.27M  69.5MB/s    in 16s     

2023-08-20 13:34:13 (56.7 MB/s) - ‘08_model_6_USE_feature_extractor.zip’ saved [960779165/960779165]



In [ ]:
!unzip /content/08_model_6_USE_feature_extractor.zip

Archive:  /content/08_model_6_USE_feature_extractor.zip
   creating: 08_model_6_USE_feature_extractor/
   creating: 08_model_6_USE_feature_extractor/assets/
   creating: 08_model_6_USE_feature_extractor/variables/
  inflating: 08_model_6_USE_feature_extractor/variables/variables.data-00000-of-00001  
  inflating: 08_model_6_USE_feature_extractor/variables/variables.index  
  inflating: 08_model_6_USE_feature_extractor/saved_model.pb  


In [ ]:
model_6_pretrained=tf.keras.models.load_model('/content/08_model_6_USE_feature_extractor')
model_6_pretrained.evaluate(val_sentences,val_labels)

24/24 [==============================] - 2s 20ms/step - loss: 0.4272 - accuracy: 0.8163


[0.42723119258880615, 0.8162729740142822]

In [ ]:
model_6_pretrained_pred_probs=model_6_pretrained.predict(val_sentences)
model_6_pretrained_preds=tf.squeeze(tf.round(model_6_pretrained_pred_probs))
model_6_pretrained_preds[:10]

24/24 [==============================] - 1s 23ms/step


<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 1., 1., 1., 1., 1., 0.], dtype=float32)>

In [ ]:
val_df=pd.DataFrame({"text":val_sentences,
                     "target":val_labels,
                     "pred":model_6_pretrained_preds,
                     "pred_prob":tf.squeeze(model_6_pretrained_pred_probs)})

In [ ]:
val_df

text  target  pred  \
0    DFR EP016 Monthly Meltdown - On Dnbheaven 2015...       0   0.0   
1    FedEx no longer to transport bioterror germs i...       0   1.0   
2    Gunmen kill four in El Salvador bus attack: Su...       1   1.0   
3    @camilacabello97 Internally and externally scr...       1   0.0   
4    Radiation emergency #preparedness starts with ...       1   1.0   
..                                                 ...     ...   ...   
757            That's the ultimate road to destruction       0   0.0   
758  @SetZorah dad why dont you claim me that mean ...       0   0.0   
759  FedEx will no longer transport bioterror patho...       0   1.0   
760  Crack in the path where I wiped out this morni...       0   1.0   
761  I liked a @YouTube video from @dannyonpc http:...       0   0.0   

     pred_prob  
0     0.159757  
1     0.747162  
2     0.988749  
3     0.196229  
4     0.707808  
..         ...  
757   0.137074  
758   0.095865  
759   0.876982  
760   0.612631  
761   0.117992  

[762 rows x 4 columns]

In [ ]:
most_wrong=val_df[val_df['target']!=val_df['pred']] .sort_values("pred_prob", ascending=False)

In [ ]:
most_wrong

text  target  pred  \
31   ? High Skies - Burning Buildings ? http://t.co...       0   1.0   
759  FedEx will no longer transport bioterror patho...       0   1.0   
628  @noah_anyname That's where the concentration c...       0   1.0   
209  Ashes 2015: Australia‰Ûªs collapse at Trent Br...       0   1.0   
251  @AshGhebranious civil rights continued in the ...       0   1.0   
..                                                 ...     ...   ...   
411  @SoonerMagic_ I mean I'm a fan but I don't nee...       1   0.0   
233                    I get to smoke my shit in peace       1   0.0   
38   Why are you deluged with low self-image? Take ...       1   0.0   
244  Reddit Will Now Quarantine‰Û_ http://t.co/pkUA...       1   0.0   
23   Ron &amp; Fez - Dave's High School Crush https...       1   0.0   

     pred_prob  
31    0.910196  
759   0.876982  
628   0.852300  
209   0.835455  
251   0.827213  
..         ...  
411   0.043918  
233   0.042087  
38    0.038998  
244   0.038949  
23    0.037186  

[140 rows x 4 columns]

In [ ]:
for row in most_wrong[:10].itertuples():
  _,text,target,pred,pred_prob=row
  print(f"Target: {target}, Pred: {pred}, Prob: {pred_prob}")
  print(f"Text:\n{text}")

Target: 0, Pred: 1.0, Prob: 0.9101957082748413
Text:
? High Skies - Burning Buildings ? http://t.co/uVq41i3Kx2 #nowplaying
Target: 0, Pred: 1.0, Prob: 0.8769820332527161
Text:
FedEx will no longer transport bioterror pathogens in wake of anthrax lab mishaps http://t.co/lHpgxc4b8J
Target: 0, Pred: 1.0, Prob: 0.8523001670837402
Text:
@noah_anyname That's where the concentration camps and mass murder come in. 
 
EVERY. FUCKING. TIME.
Target: 0, Pred: 1.0, Prob: 0.835454523563385
Text:
Ashes 2015: Australia‰Ûªs collapse at Trent Bridge among worst in history: England bundled out Australia for 60 ... http://t.co/t5TrhjUAU0
Target: 0, Pred: 1.0, Prob: 0.8272131681442261
Text:
@AshGhebranious civil rights continued in the 60s. And what about trans-generational trauma? if anything we should listen to the Americans.
Target: 0, Pred: 1.0, Prob: 0.8148159384727478
Text:
@SonofLiberty357 all illuminated by the brightly burning buildings all around the town!
Target: 0, Pred: 1.0, Prob: 0.8108397126

In [ ]:
#for i in most_wrong[:2].itertuples():
#  print(i)

In [ ]:
test_df

id keyword location  \
0         0     NaN      NaN   
1         2     NaN      NaN   
2         3     NaN      NaN   
3         9     NaN      NaN   
4        11     NaN      NaN   
...     ...     ...      ...   
3258  10861     NaN      NaN   
3259  10865     NaN      NaN   
3260  10868     NaN      NaN   
3261  10874     NaN      NaN   
3262  10875     NaN      NaN   

                                                   text  
0                    Just happened a terrible car crash  
1     Heard about #earthquake is different cities, s...  
2     there is a forest fire at spot pond, geese are...  
3              Apocalypse lighting. #Spokane #wildfires  
4         Typhoon Soudelor kills 28 in China and Taiwan  
...                                                 ...  
3258  EARTHQUAKE SAFETY LOS ANGELES ‰ÛÒ SAFETY FASTE...  
3259  Storm in RI worse than last hurricane. My city...  
3260  Green Line derailment in Chicago http://t.co/U...  
3261  MEG issues Hazardous Weather Outlook (HWO) htt...  
3262  #CityofCalgary has activated its Municipal Eme...  

[3263 rows x 4 columns]

In [ ]:
test_sentences=test_df["text"].to_list()
test_sentences[:10]

['Just happened a terrible car crash',
 'Heard about #earthquake is different cities, stay safe everyone.',
 'there is a forest fire at spot pond, geese are fleeing across the street, I cannot save them all',
 'Apocalypse lighting. #Spokane #wildfires',
 'Typhoon Soudelor kills 28 in China and Taiwan',
 "We're shaking...It's an earthquake",
 "They'd probably still show more life than Arsenal did yesterday, eh? EH?",
 'Hey! How are you?',
 'What a nice hat?',
 'Fuck off!']

In [ ]:
test_samples=random.sample(test_sentences,10)
for test_sample in test_samples:
  pred_prob=tf.squeeze(model_6_pretrained.predict([test_sample])) #model expects a list
  pred=tf.round(pred_prob)
  print(f"Pred: {int(pred)}, Prob: {pred_prob}")
  print(f"Text :\n {test_sample}")


1/1 [==============================] - 0s 66ms/step
Pred: 1, Prob: 0.9434784650802612
Text :
 Hotel arsonist who caused å£70000 damage was ‰Û÷crying for help‰Ûª: An arsonist has been jailed after a court hear... http://t.co/HNGDdBhewa
1/1 [==============================] - 0s 102ms/step
Pred: 1, Prob: 0.9042808413505554
Text :
 It doesn't get any closer. Heavy rain just barely missed @TontitownGrape festival but lightning TOO CLOSE #TGF2015 http://t.co/d9PQIXaTX6
1/1 [==============================] - 0s 92ms/step
Pred: 1, Prob: 0.9911375641822815
Text :
 Hopefully this will bring some closure for the families #MH370: Malaysian PM confirms debris is from missing flight http://t.co/2963y36LdF
1/1 [==============================] - 0s 111ms/step
Pred: 0, Prob: 0.05207646265625954
Text :
 @JuneSnowpaw Yeah Gimme dat creamy white stuff ;3
1/1 [==============================] - 0s 93ms/step
Pred: 1, Prob: 0.5504084825515747
Text :
 Deaths 5 http://t.co/0RtxTT11jj
1/1 [======================